# Generated by Django 4.2.1 on 2023-05-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
